### ISSUE TITLE
Where can i find instructions definitation?

### ISSUE THREAD

**Issue by kacpermigala** [openrisc/or1ksim#11]
I got question, where can i find instruction definition?
I need to change for example l.add instruction, so every time i put this in code i will get result +1?

**Comment by stffrdhrn** [comment]
It's probably way too late, but it's here.

https://github.com/openrisc/or1ksim/blob/or1k-master/cpu/or32/insnset.c

**Comment by stffrdhrn** [comment]
We probably should not hello with homework assignments though.  Closing
